// src/features/gdrive/googleSheetsFunctions.ts
// Catalogue des fonctions Google Sheets pour l'autocomplétion + la référence des
// colonnes-formule. Organisé en GROUPES (par catégorie) ; une liste plate est
// dérivée pour l'autocomplétion.
export interface GSheetsFunction {
  name: string
  hint: string
  /** Catégorie (groupe d'affichage). */
  cat: string
}

interface FunctionGroup {
  cat: string
  fns: { name: string; hint: string }[]
}

export const GSHEETS_FUNCTION_GROUPS: FunctionGroup[] = [
  {
    cat: 'Maths',
    fns: [
      { name: 'SUM', hint: 'Somme d’une plage' },
      { name: 'SUMIF', hint: 'Somme selon un critère' },
      { name: 'SUMIFS', hint: 'Somme selon plusieurs critères' },
      { name: 'SUMPRODUCT', hint: 'Somme des produits' },
      { name: 'PRODUCT', hint: 'Produit des valeurs' },
      { name: 'QUOTIENT', hint: 'Quotient entier' },
      { name: 'MOD', hint: 'Reste d’une division' },
      { name: 'POWER', hint: 'Puissance : POWER(base ; exp)' },
      { name: 'SQRT', hint: 'Racine carrée' },
      { name: 'EXP', hint: 'Exponentielle' },
      { name: 'LN', hint: 'Logarithme népérien' },
      { name: 'LOG', hint: 'Logarithme (base au choix)' },
      { name: 'LOG10', hint: 'Logarithme base 10' },
      { name: 'ABS', hint: 'Valeur absolue' },
      { name: 'SIGN', hint: 'Signe (-1/0/1)' },
      { name: 'INT', hint: 'Partie entière inférieure' },
      { name: 'TRUNC', hint: 'Tronque les décimales' },
      { name: 'ROUND', hint: 'ROUND(nombre ; décimales)' },
      { name: 'ROUNDUP', hint: 'Arrondi au supérieur' },
      { name: 'ROUNDDOWN', hint: 'Arrondi à l’inférieur' },
      { name: 'MROUND', hint: 'Arrondi au multiple le plus proche' },
      { name: 'CEILING', hint: 'Arrondi au multiple supérieur' },
      { name: 'FLOOR', hint: 'Arrondi au multiple inférieur' },
      { name: 'GCD', hint: 'PGCD' },
      { name: 'LCM', hint: 'PPCM' },
      { name: 'RAND', hint: 'Nombre aléatoire 0–1' },
      { name: 'RANDBETWEEN', hint: 'Entier aléatoire entre deux bornes' },
      { name: 'PI', hint: 'Constante π' },
    ],
  },
  {
    cat: 'Statistiques',
    fns: [
      { name: 'AVERAGE', hint: 'Moyenne' },
      { name: 'AVERAGEIF', hint: 'Moyenne selon un critère' },
      { name: 'AVERAGEIFS', hint: 'Moyenne selon plusieurs critères' },
      { name: 'MEDIAN', hint: 'Médiane' },
      { name: 'MODE', hint: 'Valeur la plus fréquente' },
      { name: 'MIN', hint: 'Minimum' },
      { name: 'MAX', hint: 'Maximum' },
      { name: 'MINIFS', hint: 'Minimum selon critères' },
      { name: 'MAXIFS', hint: 'Maximum selon critères' },
      { name: 'COUNT', hint: 'Compte les nombres' },
      { name: 'COUNTA', hint: 'Compte les cellules non vides' },
      { name: 'COUNTBLANK', hint: 'Compte les cellules vides' },
      { name: 'COUNTIF', hint: 'Compte selon un critère' },
      { name: 'COUNTIFS', hint: 'Compte selon plusieurs critères' },
      { name: 'COUNTUNIQUE', hint: 'Compte les valeurs uniques' },
      { name: 'LARGE', hint: 'n-ième plus grande valeur' },
      { name: 'SMALL', hint: 'n-ième plus petite valeur' },
      { name: 'RANK', hint: 'Rang d’une valeur' },
      { name: 'PERCENTILE', hint: 'Centile d’une plage' },
      { name: 'QUARTILE', hint: 'Quartile d’une plage' },
      { name: 'STDEV', hint: 'Écart-type (échantillon)' },
      { name: 'STDEVP', hint: 'Écart-type (population)' },
      { name: 'VAR', hint: 'Variance (échantillon)' },
      { name: 'VARP', hint: 'Variance (population)' },
      { name: 'CORREL', hint: 'Coefficient de corrélation' },
    ],
  },
  {
    cat: 'Texte',
    fns: [
      { name: 'CONCATENATE', hint: 'Concatène du texte' },
      { name: 'CONCAT', hint: 'Concatène deux valeurs' },
      { name: 'TEXTJOIN', hint: 'Joint avec séparateur (ignore vides)' },
      { name: 'JOIN', hint: 'Joint une plage avec séparateur' },
      { name: 'SPLIT', hint: 'Découpe du texte' },
      { name: 'LEFT', hint: 'Caractères de gauche' },
      { name: 'RIGHT', hint: 'Caractères de droite' },
      { name: 'MID', hint: 'Sous-chaîne' },
      { name: 'LEN', hint: 'Longueur du texte' },
      { name: 'TRIM', hint: 'Supprime espaces superflus' },
      { name: 'CLEAN', hint: 'Retire caractères non imprimables' },
      { name: 'UPPER', hint: 'Majuscules' },
      { name: 'LOWER', hint: 'Minuscules' },
      { name: 'PROPER', hint: 'Première lettre en majuscule' },
      { name: 'SUBSTITUTE', hint: 'Remplace un texte par un autre' },
      { name: 'REPLACE', hint: 'Remplace par position' },
      { name: 'FIND', hint: 'Position (sensible à la casse)' },
      { name: 'SEARCH', hint: 'Position (insensible à la casse)' },
      { name: 'REPT', hint: 'Répète un texte' },
      { name: 'TEXT', hint: 'TEXT(valeur ; format)' },
      { name: 'VALUE', hint: 'Convertit texte → nombre' },
      { name: 'EXACT', hint: 'Égalité stricte de deux textes' },
      { name: 'REGEXMATCH', hint: 'Teste une regex' },
      { name: 'REGEXEXTRACT', hint: 'Extrait via regex' },
      { name: 'REGEXREPLACE', hint: 'Remplace via regex' },
    ],
  },
  {
    cat: 'Logique',
    fns: [
      { name: 'IF', hint: 'IF(test ; si_vrai ; si_faux)' },
      { name: 'IFS', hint: 'Conditions multiples' },
      { name: 'IFERROR', hint: 'IFERROR(valeur ; sinon)' },
      { name: 'IFNA', hint: 'Valeur de repli si #N/A' },
      { name: 'AND', hint: 'ET logique' },
      { name: 'OR', hint: 'OU logique' },
      { name: 'NOT', hint: 'NON logique' },
      { name: 'XOR', hint: 'OU exclusif' },
      { name: 'SWITCH', hint: 'Aiguillage selon une valeur' },
      { name: 'TRUE', hint: 'Vrai' },
      { name: 'FALSE', hint: 'Faux' },
    ],
  },
  {
    cat: 'Date / heure',
    fns: [
      { name: 'TODAY', hint: 'Date du jour' },
      { name: 'NOW', hint: 'Date et heure actuelles' },
      { name: 'DATE', hint: 'DATE(année ; mois ; jour)' },
      { name: 'TIME', hint: 'TIME(h ; min ; s)' },
      { name: 'YEAR', hint: 'Année d’une date' },
      { name: 'MONTH', hint: 'Mois d’une date' },
      { name: 'DAY', hint: 'Jour d’une date' },
      { name: 'HOUR', hint: 'Heure' },
      { name: 'MINUTE', hint: 'Minute' },
      { name: 'SECOND', hint: 'Seconde' },
      { name: 'WEEKDAY', hint: 'Jour de la semaine' },
      { name: 'WEEKNUM', hint: 'Numéro de semaine' },
      { name: 'EDATE', hint: 'Date décalée de n mois' },
      { name: 'EOMONTH', hint: 'Dernier jour du mois' },
      { name: 'DATEDIF', hint: 'Différence entre deux dates' },
      { name: 'DAYS', hint: 'Nombre de jours entre deux dates' },
      { name: 'NETWORKDAYS', hint: 'Jours ouvrés entre deux dates' },
      { name: 'WORKDAY', hint: 'Date après n jours ouvrés' },
      { name: 'DATEVALUE', hint: 'Texte → date' },
    ],
  },
  {
    cat: 'Recherche / matrices',
    fns: [
      { name: 'VLOOKUP', hint: 'Recherche verticale' },
      { name: 'HLOOKUP', hint: 'Recherche horizontale' },
      { name: 'XLOOKUP', hint: 'Recherche moderne (toutes directions)' },
      { name: 'LOOKUP', hint: 'Recherche simple' },
      { name: 'INDEX', hint: 'INDEX(plage ; ligne ; col)' },
      { name: 'MATCH', hint: 'Position dans une plage' },
      { name: 'OFFSET', hint: 'Décale une référence' },
      { name: 'INDIRECT', hint: 'Référence depuis du texte' },
      { name: 'CHOOSE', hint: 'Choisit selon un index' },
      { name: 'ROW', hint: 'Numéro de ligne' },
      { name: 'ROWS', hint: 'Nombre de lignes' },
      { name: 'COLUMN', hint: 'Numéro de colonne' },
      { name: 'COLUMNS', hint: 'Nombre de colonnes' },
      { name: 'ADDRESS', hint: 'Référence A1 depuis ligne/col' },
      { name: 'HYPERLINK', hint: 'Crée un lien cliquable' },
      { name: 'ARRAYFORMULA', hint: 'Applique à toute la colonne' },
      { name: 'FILTER', hint: 'Filtre une plage selon conditions' },
      { name: 'SORT', hint: 'Trie une plage' },
      { name: 'SORTN', hint: 'Trie et garde les n premiers' },
      { name: 'UNIQUE', hint: 'Valeurs uniques' },
      { name: 'TRANSPOSE', hint: 'Transpose lignes/colonnes' },
      { name: 'FLATTEN', hint: 'Aplatit en une colonne' },
      { name: 'QUERY', hint: 'Requête type SQL sur une plage' },
      { name: 'IMPORTRANGE', hint: 'Importe depuis une autre feuille' },
    ],
  },
  {
    cat: 'Finance',
    fns: [
      { name: 'PMT', hint: 'Mensualité d’un emprunt' },
      { name: 'FV', hint: 'Valeur future' },
      { name: 'PV', hint: 'Valeur actuelle' },
      { name: 'RATE', hint: 'Taux d’intérêt' },
      { name: 'NPER', hint: 'Nombre de périodes' },
      { name: 'NPV', hint: 'Valeur actuelle nette' },
      { name: 'IRR', hint: 'Taux de rendement interne' },
    ],
  },
  {
    cat: 'Info / type',
    fns: [
      { name: 'ISBLANK', hint: 'Cellule vide ?' },
      { name: 'ISNUMBER', hint: 'Est un nombre ?' },
      { name: 'ISTEXT', hint: 'Est du texte ?' },
      { name: 'ISERROR', hint: 'Est une erreur ?' },
      { name: 'ISNA', hint: 'Est #N/A ?' },
      { name: 'ISEMAIL', hint: 'Est un e-mail ?' },
      { name: 'ISURL', hint: 'Est une URL ?' },
      { name: 'ISLOGICAL', hint: 'Est un booléen ?' },
      { name: 'N', hint: 'Convertit en nombre' },
      { name: 'NA', hint: 'Renvoie #N/A' },
    ],
  },
  {
    cat: 'Conversion / format',
    fns: [
      { name: 'TO_PERCENT', hint: 'Format pourcentage' },
      { name: 'DOLLAR', hint: 'Format monétaire' },
      { name: 'FIXED', hint: 'Nombre avec décimales fixes' },
    ],
  },
  {
    cat: 'Google',
    fns: [
      { name: 'GOOGLETRANSLATE', hint: 'Traduit un texte' },
      { name: 'GOOGLEFINANCE', hint: 'Données boursières' },
      { name: 'DETECTLANGUAGE', hint: 'Détecte la langue' },
      { name: 'IMAGE', hint: 'Insère une image depuis une URL' },
      { name: 'SPARKLINE', hint: 'Mini-graphe dans une cellule' },
    ],
  },
]

/** Liste plate (pour l'autocomplétion du champ formule). */
export const GSHEETS_FUNCTIONS: GSheetsFunction[] = GSHEETS_FUNCTION_GROUPS.flatMap((g) =>
  g.fns.map((f) => ({ ...f, cat: g.cat })),
)
